name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn -B verify --file pom.xml
    - name: Zip the target folder
      uses: montudor/action-zip@v1
      if: always()
      with:
        args: zip -qq -r target.zip target
    - name: Upload the target zip
      uses: actions/upload-artifact@v2.2.4
      if: always()
      with:
        path: target.zip
    - name: Clone testing framework
      run: git clone --recurse-submodules https://git.scc.kit.edu/IPDSnelting/mjtest.git
    - name: Run lexer tests
      working-directory: mjtest
      run: MJ_RUN="../Compiler/run" ./mjt.py lexer
    
        
